# ✅ jokes.py (new)

jokes = [
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the computer show up late? It had a hard drive!",
    "I'm on a whiskey diet. I've lost three days already.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What do you call fake spaghetti? An impasta!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I would tell you a joke about construction, but I’m still working on it.",
    "What did one wall say to the other? I’ll meet you at the corner.",
    "Why couldn’t the bicycle stand up by itself? It was two tired.",
    "Why do bees have sticky hair? Because they use honeycombs!",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why can’t you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why did the tomato blush? Because it saw the salad dressing!",
    "What do you call a belt made of watches? A waist of time.",
    "Why was the math teacher suspicious of prime numbers? They were acting odd.",
    "What did the grape do when it got stepped on? Nothing, it just let out a little wine.",
    "How do you organize a space party? You planet.",
    "What did zero say to eight? Nice belt!",
    "Why was the broom late? It swept in.",
    "Did you hear about the kidnapping at school? It’s fine, he woke up.",
    "Why don't oysters share their pearls? Because they're shellfish.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "Why did the cookie go to the doctor? It felt crummy.",
    "I used to play piano by ear, but now I use my hands.",
    "What did one hat say to the other? You stay here, I’ll go on ahead.",
    "Why was the calendar always tired? Because it had too many dates.",
    "Parallel lines have so much in common… it’s a shame they’ll never meet.",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why do cows wear bells? Because their horns don’t work.",
    "Why did the man run around his bed? Because he was trying to catch up on sleep!",
    "What do you get when you put a candle in a suit of armor? A knight light.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why did the fish blush? Because it saw the ocean’s bottom.",
    "How does a penguin build its house? Igloos it together.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "What do you get when you cross an elephant with a rhino? Elephino.",
    "What did the fish say when it hit the wall? Dam.",
    "I bought some shoes from a drug dealer. I don’t know what he laced them with, but I was tripping all day!",
    "Why did the coffee file a police report? It got mugged.",
    "Why was Cinderella so bad at soccer? Because she always ran away from the ball.",
    "What do you call a group of musical whales? An orca-stra.",
    "What do you call a dog magician? A labracadabrador.",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "How do you find Will Smith in the snow? You look for fresh prints.",
    "Why do seagulls fly over the sea? Because if they flew over the bay, they’d be bagels.",
    "How do you make holy water? You boil the hell out of it.",
    "What do you get from a pampered cow? Spoiled milk.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "What do you call two birds in love? Tweethearts.",
    "Why did the mushroom go to the party? Because he was a fungi!",
    "Why did the hipster burn his mouth? He drank coffee before it was cool.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What’s orange and sounds like a parrot? A carrot.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why are ghosts bad at lying? Because they are too transparent.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "What’s a skeleton’s least favorite room? The living room.",
    "Why did the stadium get hot after the game? All the fans left.",
    "What kind of tree fits in your hand? A palm tree.",
    "What do you get when you cross a fridge and a radio? Cool music.",
    "Why did the man stare at the orange juice carton? It said “concentrate.”",
    "What’s a vampire’s favorite fruit? A blood orange.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why didn’t the melon get married? Because it cantaloupe.",
    "What happens when frogs park illegally? They get toad.",
    "Why did the dad joke cross the road? To get to the punny side.",
    "What do you call a bear with no teeth? A gummy bear.",
    "How does a scientist freshen her breath? With experi-mints.",
    "What did one elevator say to the other? I think I’m coming down with something.",
    "Why can’t a nose be twelve inches long? Because then it’d be a foot.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "How does a dog stop a video? It presses the paws button.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "What’s brown and sticky? A stick.",
    "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
    "I used to be addicted to soap, but I’m clean now.",
    "Why did the duck get a job? He was really good at quacking the case.",
    "How do cows stay up to date? They read the moos-paper.",
    "What did one snowman say to the other? Do you smell carrots?",
    "How do you throw a party in space? You planet.",
    "Why didn’t the skeleton go to the party? He had no body to go with.",
    "What do elves learn in school? The elf-abet.",
    "Why do ghosts love elevators? Because they lift their spirits.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why did the music teacher need a ladder? To reach the high notes.",
    "How do you make an octopus laugh? With ten-tickles.",
]
